// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mscomm1.h"

/////////////////////////////////////////////////////////////////////////////
// CMscomm1

IMPLEMENT_DYNCREATE(CMscomm1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMscomm1 properties

/////////////////////////////////////////////////////////////////////////////
// CMscomm1 operations
