#if !defined(AFX_ANNOTATIONTOOL_H__B9D019FC_3427_4037_99CC_C8CC55398ADD__INCLUDED_)
#define AFX_ANNOTATIONTOOL_H__B9D019FC_3427_4037_99CC_C8CC55398ADD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeShapePanel;

/////////////////////////////////////////////////////////////////////////////
// CAnnotationTool wrapper class

class CAnnotationTool : public COleDispatchDriver
{
public:
	CAnnotationTool() {}		// Calls COleDispatchDriver default constructor
	CAnnotationTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAnnotationTool(const CAnnotationTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetPosition();
	void SetPosition(long nNewValue);
	CTeeShapePanel GetShape();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ANNOTATIONTOOL_H__B9D019FC_3427_4037_99CC_C8CC55398ADD__INCLUDED_)
