#if !defined(AFX_AXISLABELS_H__BC50142D_9A59_477A_B9DB_E40F31F5E8B4__INCLUDED_)
#define AFX_AXISLABELS_H__BC50142D_9A59_477A_B9DB_E40F31F5E8B4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeFont;

/////////////////////////////////////////////////////////////////////////////
// CAxisLabels wrapper class

class CAxisLabels : public COleDispatchDriver
{
public:
	CAxisLabels() {}		// Calls COleDispatchDriver default constructor
	CAxisLabels(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisLabels(const CAxisLabels& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetAngle();
	void SetAngle(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	CString GetDateTimeFormat();
	void SetDateTimeFormat(LPCTSTR lpszNewValue);
	CTeeFont GetFont();
	CString FormattedValue(double SomeValue);
	long GetPos();
	long Height(double SomeValue);
	long MaxWidth();
	BOOL GetOnAxis();
	void SetOnAxis(BOOL bNewValue);
	BOOL GetRoundFirstLabel();
	void SetRoundFirstLabel(BOOL bNewValue);
	long GetSeparation();
	void SetSeparation(long nNewValue);
	long GetSize();
	void SetSize(long nNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	CString GetValueFormat();
	void SetValueFormat(LPCTSTR lpszNewValue);
	long Width(double SomeValue);
	BOOL GetMultiline();
	void SetMultiline(BOOL bNewValue);
	void TeeSplitInLines(BSTR* St, LPCTSTR Separator);
	BOOL GetExponent();
	void SetExponent(BOOL bNewValue);
	long GetAlign();
	void SetAlign(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISLABELS_H__BC50142D_9A59_477A_B9DB_E40F31F5E8B4__INCLUDED_)
