#if !defined(AFX_BOXPLOTSERIES_H__22AFE377_4564_4F60_89D2_BD3B2FA11D6A__INCLUDED_)
#define AFX_BOXPLOTSERIES_H__22AFE377_4564_4F60_89D2_BD3B2FA11D6A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CBoxPlotSeries wrapper class

class CBoxPlotSeries : public COleDispatchDriver
{
public:
	CBoxPlotSeries() {}		// Calls COleDispatchDriver default constructor
	CBoxPlotSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBoxPlotSeries(const CBoxPlotSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
	CPointer GetExtrOut();
	CPen1 GetMedianPen();
	CPointer GetMildOut();
	double GetPosition();
	void SetPosition(double newValue);
	double GetWhiskerLength();
	void SetWhiskerLength(double newValue);
	CPen1 GetWhiskerPen();
	CPointer GetBox();
	double MaxXValue();
	double MinXValue();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BOXPLOTSERIES_H__22AFE377_4564_4F60_89D2_BD3B2FA11D6A__INCLUDED_)
