#if !defined(AFX_CALENDARCELL_H__53DFC920_76E4_4734_BD0B_FE95F64396F2__INCLUDED_)
#define AFX_CALENDARCELL_H__53DFC920_76E4_4734_BD0B_FE95F64396F2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeFont;
class CGradient;

/////////////////////////////////////////////////////////////////////////////
// CCalendarCell wrapper class

class CCalendarCell : public COleDispatchDriver
{
public:
	CCalendarCell() {}		// Calls COleDispatchDriver default constructor
	CCalendarCell(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCalendarCell(const CCalendarCell& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	CTeeFont GetFont();
	CGradient GetGradient();
	long GetShadowSize();
	void SetShadowSize(long nNewValue);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long newValue);
	BOOL GetTransparent();
	void SetTransparent(BOOL bNewValue);
	long GetShapeStyle();
	void SetShapeStyle(long nNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	// method 'GetShapeBounds' not emitted because of invalid return type or parameter type
	long GetBevel();
	void SetBevel(long nNewValue);
	long GetBevelWidth();
	void SetBevelWidth(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CALENDARCELL_H__53DFC920_76E4_4734_BD0B_FE95F64396F2__INCLUDED_)
