#if !defined(AFX_COLORBANDTOOL_H__24CF5135_FCC3_46C4_8A7F_A73E5BA89FD7__INCLUDED_)
#define AFX_COLORBANDTOOL_H__24CF5135_FCC3_46C4_8A7F_A73E5BA89FD7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;
class CGradient;

/////////////////////////////////////////////////////////////////////////////
// CColorBandTool wrapper class

class CColorBandTool : public COleDispatchDriver
{
public:
	CColorBandTool() {}		// Calls COleDispatchDriver default constructor
	CColorBandTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CColorBandTool(const CColorBandTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetAxis();
	void SetAxis(const VARIANT& newValue);
	CBrush1 GetBrush();
	CPen1 GetPen();
	double GetEndValue();
	void SetEndValue(double newValue);
	double GetStartValue();
	void SetStartValue(double newValue);
	BOOL GetDrawBehind();
	void SetDrawBehind(BOOL bNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	CGradient GetGradient();
	long GetTransparency();
	void SetTransparency(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COLORBANDTOOL_H__24CF5135_FCC3_46C4_8A7F_A73E5BA89FD7__INCLUDED_)
