#if !defined(AFX_EXPLODEDSLICES_H__B0243B13_4C40_465D_A5D4_61E700DDB5AE__INCLUDED_)
#define AFX_EXPLODEDSLICES_H__B0243B13_4C40_465D_A5D4_61E700DDB5AE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CExplodedSlices wrapper class

class CExplodedSlices : public COleDispatchDriver
{
public:
	CExplodedSlices() {}		// Calls COleDispatchDriver default constructor
	CExplodedSlices(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CExplodedSlices(const CExplodedSlices& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetValue(long Index);
	void SetValue(long Index, long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EXPLODEDSLICES_H__B0243B13_4C40_465D_A5D4_61E700DDB5AE__INCLUDED_)
