#if !defined(AFX_HIGHLOWSERIES_H__FBD45DBB_12BD_4C96_A03F_1A90DA44B69D__INCLUDED_)
#define AFX_HIGHLOWSERIES_H__FBD45DBB_12BD_4C96_A03F_1A90DA44B69D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;
class CValueList;

/////////////////////////////////////////////////////////////////////////////
// CHighLowSeries wrapper class

class CHighLowSeries : public COleDispatchDriver
{
public:
	CHighLowSeries() {}		// Calls COleDispatchDriver default constructor
	CHighLowSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHighLowSeries(const CHighLowSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long AddHighLow(double AX, double AHigh, double ALow, LPCTSTR AXLabel, unsigned long AColor);
	CBrush1 GetHighBrush();
	CPen1 GetHighPen();
	CValueList GetHighValues();
	CBrush1 GetLowBrush();
	CPen1 GetLowPen();
	CValueList GetLowValues();
	CPen1 GetPen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HIGHLOWSERIES_H__FBD45DBB_12BD_4C96_A03F_1A90DA44B69D__INCLUDED_)
