// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "movingavgfunction.h"


/////////////////////////////////////////////////////////////////////////////
// CMovingAvgFunction properties

/////////////////////////////////////////////////////////////////////////////
// CMovingAvgFunction operations

BOOL CMovingAvgFunction::GetWeighted()
{
	BOOL result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CMovingAvgFunction::SetWeighted(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}
