#if !defined(AFX_PAGENUMTOOL_H__C9A2AF16_FE73_4B02_89F6_10A4967786E1__INCLUDED_)
#define AFX_PAGENUMTOOL_H__C9A2AF16_FE73_4B02_89F6_10A4967786E1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeShapePanel;

/////////////////////////////////////////////////////////////////////////////
// CPageNumTool wrapper class

class CPageNumTool : public COleDispatchDriver
{
public:
	CPageNumTool() {}		// Calls COleDispatchDriver default constructor
	CPageNumTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPageNumTool(const CPageNumTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetPosition();
	void SetPosition(long nNewValue);
	CTeeShapePanel GetShape();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CString GetFormat();
	void SetFormat(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PAGENUMTOOL_H__C9A2AF16_FE73_4B02_89F6_10A4967786E1__INCLUDED_)
