#if !defined(AFX_POINTSERIES_H__AE6B7364_6CAD_44EE_89C4_568F9EC72018__INCLUDED_)
#define AFX_POINTSERIES_H__AE6B7364_6CAD_44EE_89C4_568F9EC72018__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;

/////////////////////////////////////////////////////////////////////////////
// CPointSeries wrapper class

class CPointSeries : public COleDispatchDriver
{
public:
	CPointSeries() {}		// Calls COleDispatchDriver default constructor
	CPointSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPointSeries(const CPointSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POINTSERIES_H__AE6B7364_6CAD_44EE_89C4_568F9EC72018__INCLUDED_)
