#if !defined(AFX_PRINTER_H__E9A3BE6D_B665_41A5_9B47_4AEAA6BAFBDF__INCLUDED_)
#define AFX_PRINTER_H__E9A3BE6D_B665_41A5_9B47_4AEAA6BAFBDF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPrinter wrapper class

class CPrinter : public COleDispatchDriver
{
public:
	CPrinter() {}		// Calls COleDispatchDriver default constructor
	CPrinter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPrinter(const CPrinter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetDetail();
	void SetDetail(long nNewValue);
	long GetMarginBottom();
	void SetMarginBottom(long nNewValue);
	long GetMarginLeft();
	void SetMarginLeft(long nNewValue);
	long GetMarginTop();
	void SetMarginTop(long nNewValue);
	long GetMarginRight();
	void SetMarginRight(long nNewValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	void Print();
	void PrintLandscape();
	void PrintPortrait();
	void ShowPreview();
	void PrintPartial(long Left, long Top, long Right, long Bottom);
	void BeginDoc();
	void EndDoc();
	long GetPrinterIndex();
	void SetPrinterIndex(long nNewValue);
	long GetPrinterCount();
	CString GetPrinterDescription(long Index);
	void PrintChart();
	long GetPageHeight();
	long GetPageWidth();
	CString GetJobTitle();
	void SetJobTitle(LPCTSTR lpszNewValue);
	BOOL GetPrintProportional();
	void SetPrintProportional(BOOL bNewValue);
	void PrintPartialHandle(const VARIANT& DC, long Left, long Top, long Right, long Bottom);
	void PrintPages(long FromPage, long ToPage);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PRINTER_H__E9A3BE6D_B665_41A5_9B47_4AEAA6BAFBDF__INCLUDED_)
