#if !defined(AFX_TEEFUNCTION_H__1F10C060_7A3C_45D3_840F_DCCF143807B5__INCLUDED_)
#define AFX_TEEFUNCTION_H__1F10C060_7A3C_45D3_840F_DCCF143807B5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCurveFittingFunction;
class CExpAvgFunction;
class CMovingAvgFunction;
class CStdDeviationFunction;
class CRSIFunction;
class CBollingerFunction;
class CADXFunction;
class CMACDFunction;
class CRMSFunction;
class CAverageFunction;

/////////////////////////////////////////////////////////////////////////////
// CTeeFunction wrapper class

class CTeeFunction : public COleDispatchDriver
{
public:
	CTeeFunction() {}		// Calls COleDispatchDriver default constructor
	CTeeFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeFunction(const CTeeFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetPeriod();
	void SetPeriod(double newValue);
	CCurveFittingFunction GetAsCurveFit();
	CExpAvgFunction GetAsExpAvg();
	CMovingAvgFunction GetAsMovAvg();
	long GetPeriodStyle();
	void SetPeriodStyle(long nNewValue);
	long GetPeriodAlign();
	void SetPeriodAlign(long nNewValue);
	CStdDeviationFunction GetAsStdDeviation();
	void BeginUpdate();
	void EndUpdate();
	CRSIFunction GetAsRSI();
	CBollingerFunction GetAsBollinger();
	CADXFunction GetAsADX();
	CMACDFunction GetAsMACD();
	CRMSFunction GetAsRMS();
	CAverageFunction GetAsAverage();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEFUNCTION_H__1F10C060_7A3C_45D3_840F_DCCF143807B5__INCLUDED_)
