#if !defined(AFX_TOOLS_H__A7E2C691_2F99_4440_B4A4_651AACC3D0E8__INCLUDED_)
#define AFX_TOOLS_H__A7E2C691_2F99_4440_B4A4_651AACC3D0E8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCursorTool;
class CDragMarksTool;
class CAxisArrowTool;
class CDrawLineTool;
class CNearestTool;
class CColorBandTool;
class CColorLineTool;
class CRotateTool;
class CMarksTipTool;
class CChartImageTool;
class CAnnotationTool;
class CPageNumTool;

/////////////////////////////////////////////////////////////////////////////
// CTools wrapper class

class CTools : public COleDispatchDriver
{
public:
	CTools() {}		// Calls COleDispatchDriver default constructor
	CTools(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTools(const CTools& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CCursorTool GetAsTeeCursor();
	CDragMarksTool GetAsDragMarks();
	CAxisArrowTool GetAsAxisArrow();
	CDrawLineTool GetAsDrawLine();
	CNearestTool GetAsNearest();
	CColorBandTool GetAsColorband();
	CColorLineTool GetAsColorLine();
	CRotateTool GetAsRotate();
	CMarksTipTool GetAsMarksTip();
	CChartImageTool GetAsChartImage();
	CAnnotationTool GetAsAnnotation();
	CPageNumTool GetAsPageNum();
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	CString GetDescription();
	long GetToolType();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TOOLS_H__A7E2C691_2F99_4440_B4A4_651AACC3D0E8__INCLUDED_)
