#if !defined(AFX_ZOOM_H__2D82F99F_47F9_47DB_8071_F69E14F8486C__INCLUDED_)
#define AFX_ZOOM_H__2D82F99F_47F9_47DB_8071_F69E14F8486C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;
class CBrush1;

/////////////////////////////////////////////////////////////////////////////
// CZoom wrapper class

class CZoom : public COleDispatchDriver
{
public:
	CZoom() {}		// Calls COleDispatchDriver default constructor
	CZoom(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CZoom(const CZoom& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetEnable();
	void SetEnable(BOOL bNewValue);
	BOOL GetAnimated();
	void SetAnimated(BOOL bNewValue);
	long GetAnimatedSteps();
	void SetAnimatedSteps(long nNewValue);
	void Undo();
	void ZoomRect(long Left, long Top, long Right, long Bottom);
	BOOL GetZoomed();
	CPen1 GetPen();
	long GetMinimumPixels();
	void SetMinimumPixels(long nNewValue);
	long GetMouseButton();
	void SetMouseButton(long nNewValue);
	long GetDirection();
	void SetDirection(long nNewValue);
	CBrush1 GetBrush();
	void ZoomPercent(double PercentZoom);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ZOOM_H__2D82F99F_47F9_47DB_8071_F69E14F8486C__INCLUDED_)
